In [ ]:
import numpy as np

#matrix = np.array([[0, 1, 1], [0, 0, 1], [1, 1, 1], [0, 1, 0], [1, 0, 0]])
matrix = np.array([
[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

def REF(matrix):
  offset = 0
  lead = []
  tmp = 0
  for j in range(len(matrix[0])): #строки
    for i in range(offset, len(matrix)): #столбцы
      if(matrix[i][j]) == 0:
        continue
      else:
        if i != offset & offset < len(matrix):
          matrix[[offset, i]] = matrix[[i, offset]]
        offset += 1
        lead.append(j)#лидер столбцы
        break
    for k in range(offset, len(matrix)):
      if(matrix[k][j] == 1):
        
        matrix[k] = matrix[k] ^ matrix[offset - 1]
  return matrix, lead

def RREF(matrix):
  lead = []
  matrix = matrix[~np.all(matrix == 0, axis = 1)]
  for i in reversed(range(len(matrix))):
    for j in reversed(range(len(matrix[0]))):
      if(matrix[i][j] == 0):
        continue
      for k in range(i):
        if matrix[k][j] == 1:
          lead.append(j)
          matrix[k] = matrix[k] ^ matrix[i]
  return matrix

#print(RREF(REF(matrix)))


class LinearCode:
  def __init__(self, matrix):
    self._code = matrix

  @property
  def code(self):
    return self._code

  def generating_matrix(self):
    return REF(np.matrix.copy(self.code))

  def reduced_generating_matrix(self):
    return RREF(np.matrix.copy(self.code))

  def lider(self):
    return REF(np.matrix.copy(self.code))[1]

#шаг 3
  def abbreviateMatrix(self):
    matrix, leader_columns = REF(np.matrix.copy(self.code))
    matrix = RREF(matrix)
    return np.delete(matrix, leader_columns, 1)

  def count_n_k(self):
    matrix = REF(np.matrix.copy(self.code))[0]
    matrix = matrix[~np.all(matrix == 0, axis = 1)]
    return (len(matrix[0]), len(matrix))
  
  def checkingMatrix(self):
    pass
    new_matrix = np.matrix([])
    leader = REF(np.matrix.copy(self.code))[1]
    X = self.abbreviateMatrix()
    ones_matrix = np.eye(len(matrix[0]), dtype=int)
    count = 0
    for i in range(len(matrix)): #столбцы
      for j in range(len(matrix[0])): #строки
    #for row in matrix:
        if(leader[count] == count):
          new_matrix[:, i]= matrix[:, i]
        else:
          new_matrix[:, i]= ones_matrix[:, i]
  
  def generate_all_code_words(self):
    matrix = RREF((REF(np.matrix.copy(self.code)))[0])
    code_words = []

    for row in matrix:
        code_words.append(row)

    was_added = True
    while(True):
      for i in range(len(code_words)):
        for j in range(i + 1, len(code_words), 1):
          code_word = code_words[i] ^ code_words[j]
          size = 0
          for row in code_words:
            if np.array_equal(row, code_word):
              break;
            else:
              size += 1
          if size == len(code_words):
            code_words.append(code_word)
            was_added = True
      if not was_added:
        break 
      else:
        was_added = False
        continue
    return np.array(code_words, dtype=int)

  def checkingMatrix_4step(self):
    result=[]
    matrix = self.abbreviateMatrix()
    ones_matrix = np.eye(len(matrix[0]), dtype=int)
    leader = REF(np.matrix.copy(self.code))[1]
    j=0
    k=0
    for i in range(len(matrix)+len(ones_matrix)):
        if i in leader:
            result.append(matrix[k])
            k+=1
        else:
            result.append(ones_matrix[j])
            j+=1
    
    return np.array(result)

  def multiply_by_checking(self):
    code_words = self.generate_all_code_words()
    checking_matrix = self.checkingMatrix_4step()
    result = []
    for row in code_words:
      result.append(np.dot(row, checking_matrix) % 2)
    print("res", np.array(result))
    return np.array(result, dtype=int)
###############################################
  def code_error(self):
    print("Code:\n", self.code)

    dif1 = len(self.code)
    for i1 in range(len(self.code)):
      for i2 in range(i1 + 1, len(self.code), 1):
        dif2 = 0
        for j in range(len(self.code[0])):
          if self.code[i1][j] == self.code[i2][j]:
            continue
          else:
            dif2 += 1
        if dif2 < dif1:
          dif1 = dif2

    return (dif1, (dif1- 1)/2)

  def create_error(self):
    matrix = np.matrix.copy(self.code)
    matrix[0][1] = (matrix[0][1] + 1) % 2
    #print("matrix", matrix)
    checking_matrix = self.checkingMatrix_4step()
    print("checking\n", checking_matrix)
    result = []
    for row in matrix:
      result.append(np.dot(row, checking_matrix) % 2)
    return np.array(result, dtype=int)
    

code = LinearCode(matrix)
#print(code.generating_matrix())
#print(code.count_n_k())
G = np.array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])
G_matrix = LinearCode(G)

#Зафиксировать ведущие столбцы lead матрицы G
leader = G_matrix.generating_matrix()[1]
#Шаг 1. Сформировать матрицу G∗ в приведённом ступенчатом виде на основе порождающей
G_= G_matrix.reduced_generating_matrix()
#Сформировать сокращённую матрицу X, удалив ведущие столбцы матрицы G_
X = G_matrix.abbreviateMatrix()
#print(G_)
#Сформировать матрицу H
H = G_matrix.checkingMatrix_4step()
#print(H)

#1.4 Сформировать все кодовые слова длины n двумя способами.
#Сложить все слова из порождающего множества, оставить неповторяющиеся.

#print(code.generate_all_code_words())

#print(code.multiply_by_checking())

print(code.code_error())
print(code.create_error())

Code:
 [[1 0 1 1 0 0 0 1 0 0 1]
 [0 0 0 1 1 1 0 1 0 1 0]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 1]]
(3, 1.0)
checking
 [[0 1 1 1 1 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 1 1]
 [0 0 0 1 0 1]
 [0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
[[1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
import numpy as np

matrix = np.array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
                   [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
                   [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
                   [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0],
                   [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
                   [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]])

def REF(matrix):
  offset = 0
  for j in range(len(matrix[0])): 
    for i in range(offset, len(matrix)):
      if(matrix[i][j]) == 0:
        continue
      else:
        if i != offset & offset < len(matrix):
          matrix[[offset, i]] = matrix[[i, offset]]
        offset += 1
        break
    for k in range(offset, len(matrix)):
      if(matrix[k][j] == 1):
        matrix[k] = matrix[k] ^ matrix[offset - 1]
  return matrix

def RREF(matrix):
  matrix = matrix[~np.all(matrix == 0, axis = 1)]
  for i in reversed(range(len(matrix))):
    for j in reversed(range(len(matrix[0]))):
      if(matrix[i][j] == 0):
        continue
      for k in range(i):
        if matrix[k][j] == 1:
          matrix[k] = matrix[k] ^ matrix[i]
  return matrix

print(REF(matrix))
RREF(REF(matrix))

[[1 0 1 1 0 0 0 1 0 0 1]
 [0 0 0 1 1 1 0 1 0 1 0]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0]]


array([[1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

In [ ]:
def merger(matrix, lead_col, ed_matrix):
    result=[]
    j=0
    k=0
    for i in range(len(matrix)+len(ed_matrix)):
        if i in lead_col:
            result.append(matrix[k])
            k+=1
        else:
            result.append(ed_matrix[j])
            j+=1
    return np.array(result)

#1.4

H=np.array([
    [0,1,1,1,1,0],
    [1,0,0,0,0,0],
    [0,1,0,0,0,0],
    [0,0,1,0,1,1],
    [0,0,0,1,0,1],
    [0,0,1,0,0,0],
    [0,0,0,0,1,0],
    [0,0,0,1,0,0],
    [0,0,0,0,1,1],
    [0,0,0,0,1,0],
    [0,0,0,0,0,1]])

def all_codes_words_2(matrix): #1.4.2
  result=[]
  for i in range(2**len(matrix)):
      tmp=np.zeros(len(matrix),dtype=int)
      l = int(bin(i)[2:])
      for j in range(len(tmp)):
          tmp[-1-j] = l%10
          l=l//10
      tmp=np.dot(tmp,matrix)%2
      result.append(tmp)
  return np.array(result)

#code_words_1 = all_codes_words_1(G)
code_words_2 = all_codes_words_2(G)

v=code_words_2[16]
print(v)
vH=np.dot(v,H)%2
print(vH)