In [ ]:
import numpy as np

#matrix = np.array([[0, 1, 1], [0, 0, 1], [1, 1, 1], [0, 1, 0], [1, 0, 0]])
matrix = np.array([
[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

def REF(matrix):
  offset = 0
  lead = []
  tmp = 0
  for j in range(len(matrix[0])): #строки
    for i in range(offset, len(matrix)): #столбцы
      if(matrix[i][j]) == 0:
        continue
      else:
        if i != offset & offset < len(matrix):
          matrix[[offset, i]] = matrix[[i, offset]]
        offset += 1
        lead.append(j)#лидер столбцы
        break
    for k in range(offset, len(matrix)):
      if(matrix[k][j] == 1):
        
        matrix[k] = matrix[k] ^ matrix[offset - 1]
  return matrix, lead

def RREF(matrix):
  lead = []
  matrix = matrix[~np.all(matrix == 0, axis = 1)]
  for i in reversed(range(len(matrix))):
    for j in reversed(range(len(matrix[0]))):
      if(matrix[i][j] == 0):
        continue
      for k in range(i):
        if matrix[k][j] == 1:
          lead.append(j)
          matrix[k] = matrix[k] ^ matrix[i]
  return matrix

#print(RREF(REF(matrix)))


class LinearCode:
  def __init__(self, matrix):
    self._code = matrix

  @property
  def code(self):
    return self._code

  def generating_matrix(self):
    return REF(np.matrix.copy(self.code))

  def reduced_generating_matrix(self):
    return RREF(np.matrix.copy(self.code))

  def lider(self):
    return REF(np.matrix.copy(self.code))[1]

#шаг 3
  def abbreviateMatrix(self):
    matrix, leader_columns = REF(np.matrix.copy(self.code))
    matrix = RREF(matrix)
    return np.delete(matrix, leader_columns, 1)

  def count_n_k(self):
    matrix = REF(np.matrix.copy(self.code))[0]
    matrix = matrix[~np.all(matrix == 0, axis = 1)]
    return (len(matrix[0]), len(matrix))
  
  def checkingMatrix(self):
    pass
    new_matrix = np.matrix([])
    leader = REF(np.matrix.copy(self.code))[1]
    X = self.abbreviateMatrix()
    ones_matrix = np.eye(len(matrix[0]), dtype=int)
    count = 0
    for i in range(len(matrix)): #столбцы
      for j in range(len(matrix[0])): #строки
    #for row in matrix:
        if(leader[count] == count):
          new_matrix[:, i]= matrix[:, i]
        else:
          new_matrix[:, i]= ones_matrix[:, i]
  
  def generate_all_code_words(self):
    matrix = RREF((REF(np.matrix.copy(self.code)))[0])
    code_words = []

    for row in matrix:
        code_words.append(row)

    was_added = True
    while(True):
      for i in range(len(code_words)):
        for j in range(i + 1, len(code_words), 1):
          code_word = code_words[i] ^ code_words[j]
          size = 0
          for row in code_words:
            if np.array_equal(row, code_word):
              break;
            else:
              size += 1
          if size == len(code_words):
            code_words.append(code_word)
            was_added = True
      if not was_added:
        break 
      else:
        was_added = False
        continue
    return np.array(code_words, dtype=int)

  def checkingMatrix_4step(self):
    result=[]
    matrix = self.abbreviateMatrix()
    ones_matrix = np.eye(len(matrix[0]), dtype=int)
    leader = REF(np.matrix.copy(self.code))[1]
    j=0
    k=0
    for i in range(len(matrix)+len(ones_matrix)):
        if i in leader:
            result.append(matrix[k])
            k+=1
        else:
            result.append(ones_matrix[j])
            j+=1
    
    return np.array(result)

  def multiply_by_checking(self):
    code_words = self.generate_all_code_words()
    checking_matrix = self.checkingMatrix_4step()
    result = []
    for row in code_words:
      result.append(np.dot(row, checking_matrix) % 2)
    print("res", np.array(result))
    return np.array(result, dtype=int)
###############################################
  def code_error(self):
    print("Code:\n", self.code)

    dif1 = len(self.code)
    for i1 in range(len(self.code)):
      for i2 in range(i1 + 1, len(self.code), 1):
        dif2 = 0
        for j in range(len(self.code[0])):
          if self.code[i1][j] == self.code[i2][j]:
            continue
          else:
            dif2 += 1
        if dif2 < dif1:
          dif1 = dif2

    return (dif1, (dif1- 1)/2)

  def create_error(self):
    matrix = np.matrix.copy(self.code)
    matrix[0][1] = (matrix[0][1] + 1) % 2
    #print("matrix", matrix)
    checking_matrix = self.checkingMatrix_4step()
    print("checking\n", checking_matrix)
    result = []
    for row in matrix:
      result.append(np.dot(row, checking_matrix) % 2)
    return np.array(result, dtype=int)
    

code = LinearCode(matrix)
#print(code.generating_matrix())
#print(code.count_n_k())
G = np.array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])
G_matrix = LinearCode(G)

#Зафиксировать ведущие столбцы lead матрицы G
leader = G_matrix.generating_matrix()[1]
#Шаг 1. Сформировать матрицу G∗ в приведённом ступенчатом виде на основе порождающей
G_= G_matrix.reduced_generating_matrix()
#Сформировать сокращённую матрицу X, удалив ведущие столбцы матрицы G_
X = G_matrix.abbreviateMatrix()
#print(G_)
#Сформировать матрицу H
H = G_matrix.checkingMatrix_4step()
#print(H)

#1.4 Сформировать все кодовые слова длины n двумя способами.
#Сложить все слова из порождающего множества, оставить неповторяющиеся.

#print(code.generate_all_code_words())

#print(code.multiply_by_checking())

print(code.code_error())
print(code.create_error())

Code:
 [[1 0 1 1 0 0 0 1 0 0 1]
 [0 0 0 1 1 1 0 1 0 1 0]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 1]]
(3, 1.0)
checking
 [[0 1 1 1 1 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 1 1]
 [0 0 0 1 0 1]
 [0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
[[1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


2.1. Сформировать порождающую матрицу линейного кода (7, 4, 3).image.png

In [ ]:
Gmatrix = np.array([
[1, 0, 0, 0, 1, 1, 0],
[0, 1, 0, 0, 0, 1, 1],
[0, 0, 1, 0, 1, 1, 1],
[0, 0, 0, 1, 1, 0, 1]])

n= 7
k= 4 
d=3

#1.1
I_k=np.eye(k, dtype=int)
X_743=np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 0, 1]], dtype=int)

G=np.concatenate((I_k, X_743),axis=1 )
#print(G_k)
#1.2
I_nk=np.eye(n-k, dtype=int)
H=np.concatenate((X_743,I_nk),axis=0)
print(H)

#1.3
Syndrome=H
#1.4
#wordN =np.array([[1, 0, 0, 0, 1, 1, 0]]) 
#wordK =np.array([[1, 0, 0, 0]]) 
#errN = np.array([[1, 0, 1, 0]]) 
#errK = np.array([[1, 0, 1, 0, 1, 0, 0]]) 
#res = np.dot(errK,G_nk)%2
#print(res)

word = np.array([1, 0, 0, 1])
code_word = np.dot(word, G) % 2
print("Code word with length of n:", code_word)

code_word_err = np.matrix.copy(code_word)
code_word_err[2] = 1
print("Code word with error:", code_word_err)

syndrome = np.dot(code_word_err, H) % 2
print("Syndrome:", syndrome)

for i in range(len(H)):
  if np.array_equal(H[i], syndrome):
    num_of_row = i
    print("Number of row in H:", num_of_row)   

err = np.zeros(len(H), dtype=int)
err[num_of_row] = 1
code_word_corr = err ^ code_word_err
print("Corrected word:", code_word_corr)

code_word_err[1] = 1
print("Code word with double error:", code_word_err)
syndrome = np.dot(code_word_err, H) % 2
print("Syndrome:", syndrome)

for i in range(len(H)):
  if np.array_equal(H[i], syndrome):
    num_of_row = i
    print("Number of row in H:", num_of_row)   

err = np.zeros(len(H), dtype=int)
err[num_of_row] = 1
code_word_corr = err ^ code_word_err
print("Corrected word:", code_word_corr)

################3


[[1 1 0]
 [0 1 1]
 [1 1 1]
 [1 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
Code word with length of n: [1 0 0 1 0 1 1]
Code word with error: [1 0 1 1 0 1 1]
Syndrome: [1 1 1]
Number of row in H: 2
Corrected word: [1 0 0 1 0 1 1]
Code word with double error: [1 1 1 1 0 1 1]
Syndrome: [1 0 0]
Number of row in H: 4
Corrected word: [1 1 1 1 1 1 1]


In [ ]:
import numpy as np
def number_2_6():
    n=int(input())
    k=int(input())
    
    I_5=np.eye(k,dtype=int)
    
    res=[]
    size=0
    for i in range(2**(n-k)):
        l = int(bin(i)[2:])
        temp=[0 for p in range(n-k)]
        count=0
        m=len(temp)-1
        while (l>0):
            if l%10 == 1: 
                count+=1
            temp[m]=l%10
            l=l//10
            m-=1
        if count>=4:
            #проверка на сумму 2
            cnt_min=len(temp)+1
            for e in range(len(res)):
                cnt=0
                for b in range(len(temp)):
                    if temp[b]!=res[e][b]:
                        cnt+=1
                if cnt<cnt_min:
                    cnt_min=cnt
            if cnt_min<3:
                continue

            #проверка на сумму 3
            cnt_min=len(temp)+1
            for e in range(len(res)):
                for w in range(len(res)):
                    if e==w:
                        continue
                    cnt=0
                    for b in range(len(temp)):
                        if (temp[b]+res[e][b]+res[w][b])%2==1:
                            cnt+=1
                    if cnt<cnt_min:
                        cnt_min=cnt
            if cnt_min<2:
                continue

            #проверка на сумму 4 
            cnt_min=len(temp)+1
            for e in range(len(res)):
                for w in range(len(res)):
                    for u in range(len(res)):
                        if e==w or e==u or w==u:
                            continue
                        cnt=0
                        for b in range(len(temp)):
                            if (temp[b]+res[e][b]+res[w][b]+res[u][b])%2==1:
                                cnt+=1
                        if cnt<cnt_min:
                            cnt_min=cnt
            if cnt_min<1:
                continue

            res.append(temp)
            size+=1
        if size==k:
            break
    if size!=k:
        print("error size")
        return
    X_5 = np.array(res)
    #print(X_5)

    G_nk5=np.concatenate((I_5,X_5),axis=1)
    print(G_nk5)

    I_5=np.eye(n-k,dtype=int)
    H_nk5=np.concatenate((X_5,I_5),axis=0)
    print(H_nk5)
    return G_nk5,H_nk5

def number_2_8(G_nk5,H_nk5):
    
    k=len(G_nk5)
    n=len(H_nk5)

    #однократ
    table_one_syndroms=[]

    for i in range(2**(n-k)):
        l = int(bin(i)[2:])
        #word=np.zeros((1,k),dtype=int)
        word=[0 for s in range(k)]
        m=len(word)-1
        while (l>0):
            word[m]=l%10
            l=l//10
            m-=1
        word=np.dot(word,G_nk5)%2
        for p in range(len(word)):
            word1=word.copy()
            word1[p]+=1
            word1[p]=word1[p]%2
            word1=np.dot(word1,H_nk5)%2
            if word1.tolist() not in table_one_syndroms:
                table_one_syndroms.append(word1.tolist())


    #двукрат
    table_two_syndroms=[]
    for i in range(2**(n-k)):
        l = int(bin(i)[2:])
        #word=np.zeros((1,k),dtype=int)
        word=[0 for s in range(k)]
        m=len(word)-1
        while (l>0):
            word[m]=l%10
            l=l//10
            m-=1
        word=np.dot(word,G_nk5)%2
        for p in range(len(word)):
            for y in range(len(word)):
                #if p==y:
                #    continue
                word1=word.copy()
                word1[p]+=1
                word1[p]=word1[p]%2
                word1[y]+=1
                word1[y]=word1[y]%2
                word1=np.dot(word1,H_nk5)%2
                #if word1.tolist() not in table_two_syndroms:
                table_two_syndroms.append(word1.tolist())
    return table_one_syndroms, table_two_syndroms


def number_2_9(G,H,one_s,two_s):
    from random import randint
    k=len(G)
    n=len(H)
    word=np.array([randint(0,10)%2 for i in range(k)])
    print(word)
    word = np.dot(word,G)%2
    print("word",word)

    #добавим ошибку
    error_number = np.zeros(len(word),dtype=int)
    error_number[randint(0,len(word)-1)]=1
    print ("error - ",error_number)
    word = (word + error_number)%2

    print("word+error",word)

    ind=0
    syndrome = np.dot(word,H)%2
    print("syndrome - ",syndrome)


    for i in range(len(one_s)):
        count=0
        for j in range(len(one_s[i])):
            if one_s[i][j]==syndrome[j]:
                count+=1
        if count==len(syndrome):
            ind = i
            break
    print("index of table syndroms:",ind)
    fix = np.zeros(len(word),dtype=int)
    fix[ind]=1
    word = (word + fix)%2
    print(word[:k])


def number_2_10(G,H,one_s,two_s):
    from random import randint
    k=len(G)
    n=len(H)
    word=np.array([randint(0,10)%2 for i in range(k)])
    print(word)
    word = np.dot(word,G)%2
    print("word",word)

    #добавим ошибку
    error_number = np.zeros(len(word),dtype=int)
    number_of_error = randint(0,len(word)-1)
    error_number[number_of_error]=1
    number_of_error_2 = randint(0,len(word)-1)
    while number_of_error_2 == number_of_error:
        number_of_error_2 = randint(0,len(word)-1)
        
    error_number[number_of_error_2]=1
    print ("error - ",error_number)
    word = (word + error_number)%2

    print("word+error",word)

    ind=0
    syndrome = np.dot(word,H)%2
    print("syndrome - ",syndrome)

    """
    for i in range(len(two_s)):
        count=0
        for j in range(len(two_s[i])):
            if two_s[i][j]==syndrome[j]:
                count+=1
        if count==len(syndrome):
            ind = i
            break
    fix = np.zeros(len(word),dtype=int)
    fix[ind]=1
    word = (word + fix)%2
    """
    for i in range(len(two_s)):
        count=0
        for j in range(len(two_s[i])):
            if two_s[i][j]==syndrome[j]:
                count+=1
        if count==len(syndrome):
            ind = i
            break
    fix = np.zeros(len(word),dtype=int)
    print(two_s[ind],ind//len(word),ind%len(word))
    #fix[ind]=1
    fix[ind//len(word)] = 1
    fix[ind%len(word)] = 1
    word = (word + fix)%2
    #for i in range(len(two_s)):
    #    count=0
    #    for j in range(len(two_s[i])):
    #        if two_s[i][j]==syndrome[j]:
    #            count+=1
    #    if count==len(syndrome):
    #        ind = i
    #        break
    #fix = np.zeros(len(word),dtype=int)
    #fix[ind]=1
    #word = (word + fix)%2
    print(word[:k])


def number_2_11(G,H,one_s,two_s):
    from random import randint
    k=len(G)
    n=len(H)
    word=np.array([randint(0,10)%2 for i in range(k)])
    print(word)
    word = np.dot(word,G)%2
    print("word",word)

    #добавим ошибку
    error_number = np.zeros(len(word),dtype=int)
    number_of_error = randint(0,len(word)-1)
    error_number[number_of_error]=1
    number_of_error_2 = randint(0,len(word)-1)
    while number_of_error_2 == number_of_error:
        number_of_error_2 = randint(0,len(word)-1)
    error_number[number_of_error_2]=1    
        
    number_of_error_3 = randint(0,len(word)-1)
    while number_of_error_3 == number_of_error or number_of_error_3== number_of_error_2:
        number_of_error_3 = randint(0,len(word)-1)
    error_number[number_of_error_3]=1
    print ("error - ",error_number)
    word = (word + error_number)%2

    print("word+error",word)

    ind=0
    syndrome = np.dot(word,H)%2
    print("syndrome - ",syndrome)



    """
    for i in range(len(two_s)):
        count=0
        for j in range(len(two_s[i])):
            if two_s[i][j]==syndrome[j]:
                count+=1
        if count==len(syndrome):
            ind = i
            break
    fix = np.zeros(len(word),dtype=int)
    fix[ind]=1
    word = (word + fix)%2
    """
    t=True
    for i in range(len(one_s)):
        count=0
        for j in range(len(one_s[i])):
            if two_s[i][j]==syndrome[j]:
                count+=1
        if count==len(syndrome):
            ind = i
            t=False
            break
    if not t:
        fix = np.zeros(len(word),dtype=int)
        fix[ind]=1
        word = (word + fix)%2
        print(word[:k])
        return
    for i in range(len(two_s)):
        count=0
        for j in range(len(two_s[i])):
            if two_s[i][j]==syndrome[j]:
                count+=1
        if count==len(syndrome):
            ind = i
            t=False
            break
    
    fix = np.zeros(len(word),dtype=int)
    fix[ind//len(word)]=1
    fix[ind%len(word)]=1
    word = (word + fix)%2

    print(word[:k])



#number_2_4()
#number_2_5()
G,H=number_2_6()
one_s,two_s=number_2_8(G,H)
print("однократ")
number_2_9(G,H,one_s,two_s)
#print(np.array(two_s))
print("двукрат")
number_2_10(G,H,one_s,two_s)
print("трекрат")
number_2_11(G,H,one_s,two_s)

15
6
[[1 0 0 0 0 0 0 0 0 0 0 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 1 1 0 0 1 1]
 [0 0 1 0 0 0 0 0 1 0 1 0 1 0 1]
 [0 0 0 1 0 0 0 0 1 1 0 1 0 1 0]
 [0 0 0 0 1 0 0 1 0 0 1 0 1 1 0]
 [0 0 0 0 0 1 0 1 0 1 0 1 0 1 1]]
[[0 0 0 0 0 1 1 1 1]
 [0 0 0 1 1 0 0 1 1]
 [0 0 1 0 1 0 1 0 1]
 [0 0 1 1 0 1 0 1 0]
 [0 1 0 0 1 0 1 1 0]
 [0 1 0 1 0 1 0 1 1]
 [1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]
однократ
[0 0 0 0 0 0]
word [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
error -  [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
word+error [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
syndrome -  [0 0 1 1 0 1 0 1 0]
index of table syndroms: 3
[0 0 0 0 0 0]
двукрат
[1 0 1 0 0 1]
word [1 0 1 0 0 1 0 1 1 1 1 0 0 0 1]
error -  [0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]
word+error [1 0 1 0 0 1 0 1 1 1 0 0 0 0 0]
syndrome -  [0 0 0 0 1 0 0 0 1]
[0, 0, 0, 0, 1, 0, 0, 0, 1] 10 14
[1 0 1 0 0 1]
трекрат
[0 1 1 0 1 1]
word [0 1 1 0 1 1 